# Generated by Django 5.2.1 on 2025-06-04 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='via',
        ),
        migrations.AddField(
            model_name='user',
            name='verify_type',
            field=models.CharField(choices=[('email', 'Email'), ('phone', 'Phone')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='auth_state',
            field=models.CharField(choices=[('begin', 'Begin'), ('date_of_birth', 'Date of Birth'), ('verified', 'Verified'), ('completed', 'Completed')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True),
        ),
    ]
